name: Release

on: [push]

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types: 
#       - completed

jobs:
  release:
    name: build release
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macOS-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo build
        run: cargo build --release --no-default-features

      - name: Package
        shell: bash
        run: |
          target=$(gcc -dumpmachine)
          cd target/release          
          strip t_rex
          tar czf ../../t-rex-$target.tar.gz t_rex
          
      # - name: Publish
      #   uses: softprops/action-gh-release@v1
      #   # TODO: if any of the build step fails, the release should be deleted.
      #   with:
      #       files: 't-rex*'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
  deb:
    name: Build deb package
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04']

    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install libgdal-dev
        run: sudo apt install -y libgdal-dev

      - run: cargo install cargo-deb
      - run: cargo deb
      - run: dpkg -I target/debian/t-rex_*.deb
      - run: dpkg -c target/debian/t-rex_*.deb


  docker-release:
    name: Docker release
    needs: [deb]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: cp target/debian/t-rex_*.deb packaging/docker/
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sourcepole/t-rex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
